blank_issues_enabled: false
contact_links: []

pull_request_templates:
  - name: Feature
    path: .github/PULL_REQUEST_TEMPLATE/feature.md
  - name: Bugfix
    path: .github/PULL_REQUEST_TEMPLATE/bugfix.md
